### ISSUE TITLE
jei.zs issue line 34 and 35

### ISSUE THREAD

**Issue by kreezxil** [SmileycorpMC/ldoh-tweaks#10]
You removed hundreddayz mod and now players complain about the error. Also, Crafttweaker disables an entire script if just one part of it errors out, so you've broken your pack without realizing it.

LDOH_0.4.7HF

I've corrected the script.

[jei.zs.zip](https://github.com/SmileycorpMC/ldoh-tweaks/files/12041966/jei.zs.zip)

**Comment by SmileycorpMC** [comment]
The hundreddayz mod isn't supposed to be removed, if it is, that's an even bigger issue.

**Comment by SmileycorpMC** [comment]
The mod is definitely in the pack, apparently it's just an issue with the server pack, I'll fix that now.

**Comment by kreezxil** [comment]
ok, but it's missing from the client pack too. It's probably not missing
from your dev copy, but what's coming from CF, it's missing there. I was
hoping you were on the partner discord so I could've just showed it to you
there. I reported this issue on behalf of a bh customer that was in the
regular bh discord.

**Comment by kreezxil** [comment]
![image](https://github.com/SmileycorpMC/ldoh-tweaks/assets/3880072/d8a088c3-3be6-4b92-b351-be4c63650d4f)
That's from the client pack.

**Comment by SmileycorpMC** [comment]
I did a fresh install straight from curseforge yesterday, when you brought this up and the mod was in, I'll do some more investigating because this is very strange.

**Comment by SmileycorpMC** [comment]
Ah wait, hundreddayz is the modid of the LDoH tweaks mod, I think that's why it's not showing up on your screen as hundreddayz.
