### ISSUE TITLE
Server crashing when encountering spy

### ISSUE THREAD

**Issue by NIKKObwoy** [SmileycorpMC/ldoh-tweaks#16]
[crash-2023-11-27_10.02.22-server.txt](https://github.com/SmileycorpMC/ldoh-tweaks/files/13472780/crash-2023-11-27_10.02.22-server.txt)

It started off when I was fighting a horde and a 'BLU team' was behind me helping, then suddenly I was kicked out and our server crashed (We are using BisectHosting)

We tried reinstalling the modpack server side and client side but no luck

**Comment by SmileycorpMC** [comment]
Update the pack, this issue should have been fixed in 0.5.2-hf.
