### ISSUE TITLE
parasites phazing threw blocks

### ISSUE THREAD

**Issue by Sparkergaming** [SmileycorpMC/ldoh-tweaks#18]
yo so they paracites can phase threw blocks by making the block into a red ish blcok and goinng  threw it like its not there making bace building irelevent just wondering how i can fix that
![Screenshot_1301](https://github.com/SmileycorpMC/ldoh-tweaks/assets/20696690/2a8fad6c-918f-443f-806f-33908dacc018)

this is a picture of what they do

**Comment by SmileycorpMC** [comment]
This is intended behaviour.
