### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by ghost** [SmileycorpMC/ldoh-tweaks#2]
The latest version is not starting. The game crashes every time.
![image](https://user-images.githubusercontent.com/97146390/205981180-1e1b9eec-0b41-4b36-b8e9-f537273775b6.png)

**Comment by SmileycorpMC** [comment]
Can you send the crash report it gives you?

**Comment by ghost** [comment]
[crash-2022-12-06_23.27.17-client.txt](https://github.com/SmileycorpMC/ldoh-tweaks/files/10172395/crash-2022-12-06_23.27.17-client.txt)

**Comment by ghost** [comment]
> Can you send the crash report it gives you?

Here is it [crash-2022-12-06_23.27.17-client.txt](https://github.com/SmileycorpMC/ldoh-tweaks/files/10172395/crash-2022-12-06_23.27.17-client.txt)

**Comment by SmileycorpMC** [comment]
Unfortunately this isn't an issue that can easily be fixed on our end, it's an issue with animania, you might be able to get help from them. I will have a look at it though and see if there's anything that can be done on our end.

https://github.com/capnkirok/animaniamod/issues

**Comment by ghost** [comment]
> Unfortunately this isn't an issue that can easily be fixed on our end, it's an issue with animania, you might be able to get help from them. I will have a look at it though and see if there's anything that can be done on our end.
> 
> https://github.com/capnkirok/animaniamod/issues

Thanks for helping
