### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by lullabje** [SmileycorpMC/ldoh-tweaks#8]
![Screenshot 2023-06-04 145042](https://github.com/SmileycorpMC/ldoh-tweaks/assets/69719904/36bf088f-fa70-4207-8032-b5dcb59ae095)

My game keeps on crashing and it gives this screen, what do i do to fix it?

https://mclo.gs/kQ7Ir0I

Crash log^

**Comment by SmileycorpMC** [comment]
What happens before your game crashes?
